[workspace]
resolver = "2"
members = [
    "inox2d",
    "inox2d-opengl",
    "inox2d-wgpu",
    "inox2d-bevy",
    "examples/common",
    "examples/render-bevy",
    "examples/render-opengl",
    "examples/render-webgl",
    "examples/render-wgpu",
]
